

#include <stdio.h>
#include <stdlib.h>
#include "Enclave_u.h"// generated by sgx_edger8r



// void ocall_print_int( int i)
// {
 
//  printf("%d\n",i );

// }
void ocall_print_pointer( char *s)
{
 
 printf("%s",s);

}


sgx_status_t save_data(const char* fileName, void* data, long length){

	FILE *fp = fopen(fileName, "ab");

	if(!fp){
      return SGX_ERROR_UNEXPECTED;
    }

	int ret = fwrite(data, sizeof(uint8_t), length, fp);

    fclose(fp);

	if (ret != length) {
	    printf("writeFile: Error %d\n", ret);
	    return SGX_ERROR_UNEXPECTED;
	}

    return SGX_SUCCESS;
}

void ocall_sleep(void)
{
 	printf("%s\n","sleepping 5sec..." );
	sleep(5);
}

